#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the kangaroo function below.
def kangaroo(x1, v1, x2, v2):
    flag =0
    if ((v1 >= 1 & v1<= 10000) & (v2 >= 1 & v2<= 10000) & (x1 >= 0 & x2<=10000) & (x1 <= x2)):
        for i in range(10000):
            d1 = x1 + v1
            d2 = x2 + v2
            if(d1 == d2):
                flag = 1
                break
            else:
                x1 = d1
                x2 = d2
        
    if (flag == 1):
        var = "YES"
    else:
        var = "NO"

    return var

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    x1V1X2V2 = input().split()

    x1 = int(x1V1X2V2[0])

    v1 = int(x1V1X2V2[1])

    x2 = int(x1V1X2V2[2])

    v2 = int(x1V1X2V2[3])

    result = kangaroo(x1, v1, x2, v2)

    fptr.write(result + '\n')

    fptr.close()
